146-user about field
Hawaiideveloper/nodeJS_SocialMediaSite pull request #29
Opened 2020-10-14 01:05 UTC by ervinj1998

agregando about a la base de datos

2020-10-14 14:22 UTC, Hawaiideveloper commented
![Screen Shot 2020-10-14 at 10 27 24 AM](https://user-images.githubusercontent.com/13468708/96002465-226c1280-0e07-11eb-9c86-3f63dbea1d24.png)

2020-10-14 14:25 UTC, Hawaiideveloper requested changes
please leave comments as to what this does @ervinj1998

2020-10-15 02:29 UTC, manzanarez83 commented on routes/user.js
> -
with the following variable:
**userPhoto,
 } = require("../controllers/user");**  
allows to see the photo on the Frontend.

2020-10-15 03:55 UTC, manzanarez83 commented on routes/user.js
> + } = require("../controllers/user");  //getUser imported by object destruct
with the following variable:
**userPhoto,
 } = require("../controllers/user");**  
allows to see the photo on the Frontend.

2020-10-15 20:31 UTC, merged